# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-14 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, 'VIP'), (3, 'SVIP')], default=1),
        ),
    ]
